export default {
  data: [
    { time: "0:0", note: 0, duration: 1 },
    { time: "0:1", note: 1, duration: 1 },
    { time: "0:2", note: 2, duration: 1 },
    { time: "0:3", note: 3, duration: 1 },
    { time: "1:0", note: 4, duration: 1 },
    { time: "1:1", note: 5, duration: 1 },
    { time: "1:2", note: 6, duration: 1 },
    { time: "1:3", note: 7, duration: 1 },
    { time: "2:0", note: 8, duration: 1 },
    { time: "2:1", note: 9, duration: 1 },
    { time: "2:2", note: 10, duration: 1 },
    { time: "2:3", note: 11, duration: 1 },
    { time: "3:2", note: 0, octave: 1, duration: 1 },
    { time: "3:3", note: 1, octave: 1, duration: 1 },
    { time: "4:0", note: 2, octave: 1, duration: 1 },
    { time: "4:1", note: 3, octave: 1, duration: 1 },
    { time: "4:2", note: 4, octave: 1, duration: 1 },
    { time: "4:3", note: 5, octave: 1, duration: 1 },
    { time: "5:0", note: 6, octave: 1, duration: 1 },
    { time: "5:1", note: 7, octave: 1, duration: 1 },
    { time: "5:2", note: 8, octave: 1, duration: 1 },
    { time: "5:3", note: 9, octave: 1, duration: 1 },
    { time: "6:0", note: 10, octave: 1, duration: 1 },
    { time: "6:1", note: 11, octave: 1, duration: 1 },
    { time: "7:0", note: 0, octave: 2, duration: 1 },
    { time: "7:1", note: 1, octave: 2, duration: 1 },
    { time: "7:2", note: 2, octave: 2, duration: 1 },
    { time: "7:3", note: 3, octave: 2, duration: 1 },
    { time: "8:0", note: 4, octave: 2, duration: 1 },
    { time: "8:1", note: 5, octave: 2, duration: 1 },
    { time: "8:2", note: 6, octave: 2, duration: 1 },
    { time: "8:3", note: 7, octave: 2, duration: 1 },
    { time: "9:0", note: 8, octave: 2, duration: 1 },
    { time: "9:1", note: 9, octave: 2, duration: 1 },
    { time: "9:2", note: 10, octave: 2, duration: 1 },
    { time: "9:3", note: 11, octave: 2, duration: 1 },
    { time: "10:0" },
  ],
};
