export default {
  data: [
    { time: "0:0", note: 3, duration: 1 },
    { time: "0:1", note: 2, duration: 1 },
    { time: "0:2", note: 1, duration: 1 },
    { time: "0:3", note: 2, duration: 1 },
    { time: "1:0", note: 3, duration: 1 },
    { time: "1:1", note: 3, duration: 1 },
    { time: "1:2", note: 3, duration: 2 },
    { time: "2:0", note: 2, duration: 1 },
    { time: "2:1", note: 2, duration: 1 },
    { time: "2:2", note: 2, duration: 2 },
    { time: "3:0", note: 3, duration: 1 },
    { time: "3:1", note: 5, duration: 1 },
    { time: "3:2", note: 5, duration: 2 },
    { time: "4:0", note: 3, duration: 1 },
    { time: "4:1", note: 2, duration: 1 },
    { time: "4:2", note: 1, duration: 1 },
    { time: "4:3", note: 2, duration: 1 },
    { time: "5:0", note: 3, duration: 1 },
    { time: "5:1", note: 3, duration: 1 },
    { time: "5:2", note: 3, duration: 1 },
    { time: "5:3", note: 1, duration: 1 },
    { time: "6:0", note: 2, duration: 1 },
    { time: "6:1", note: 2, duration: 1 },
    { time: "6:2", note: 3, duration: 1 },
    { time: "6:3", note: 2, duration: 1 },
    { time: "7:0", note: 1, duration: 4 },
    { time: "8:0" },
  ],
};
