export default {
  data: [
    { time: "0:0", chord: 1, duration: 1 },
    { time: "0:1", chord: 1, duration: 1 },
    { time: "0:2", chord: 5, duration: 1 },
    { time: "0:3", chord: 5, duration: 1 },
    { time: "1:0", chord: 6, duration: 1 },
    { time: "1:1", chord: 6, duration: 1 },
    { time: "1:2", chord: 5, duration: 2 },
    { time: "2:0", chord: 4, duration: 1 },
    { time: "2:1", chord: 4, duration: 1 },
    { time: "2:2", chord: 3, duration: 1 },
    { time: "2:3", chord: 3, duration: 1 },
    { time: "3:0", chord: 2, duration: 1 },
    { time: "3:1", chord: 2, duration: 1 },
    { time: "3:2", chord: 1, duration: 2 },
    { time: "4:0", chord: 5, duration: 1 },
    { time: "4:1", chord: 5, duration: 1 },
    { time: "4:2", chord: 4, duration: 1 },
    { time: "4:3", chord: 4, duration: 1 },
    { time: "5:0", chord: 3, duration: 1 },
    { time: "5:1", chord: 3, duration: 1 },
    { time: "5:2", chord: 2, duration: 2 },
    { time: "6:0", chord: 5, duration: 1 },
    { time: "6:1", chord: 5, duration: 1 },
    { time: "6:2", chord: 4, duration: 1 },
    { time: "6:3", chord: 4, duration: 1 },
    { time: "7:0", chord: 3, duration: 1 },
    { time: "7:1", chord: 3, duration: 1 },
    { time: "7:2", chord: 2, duration: 2 },
    { time: "8:0", chord: 1, duration: 1 },
    { time: "8:1", chord: 1, duration: 1 },
    { time: "8:2", chord: 5, duration: 1 },
    { time: "8:3", chord: 5, duration: 1 },
    { time: "9:0", chord: 6, duration: 1 },
    { time: "9:1", chord: 6, duration: 1 },
    { time: "9:2", chord: 5, duration: 2 },
    { time: "10:0", chord: 4, duration: 1 },
    { time: "10:1", chord: 4, duration: 1 },
    { time: "10:2", chord: 3, duration: 1 },
    { time: "10:3", chord: 3, duration: 1 },
    { time: "11:0", chord: 2, duration: 1 },
    { time: "11:1", chord: 2, duration: 1 },
    { time: "11:2", chord: 1, duration: 2 },
  ],
};
